version: '3.7'
services:
  my-file-service:
    image: my-file-service:latest
    build:
      target: app
      dockerfile: Dockerfile
      context: .
    environment:
      LOG_LEVEL: "debug"
      STORE_ENDPOINT: "http://minio:9000"
      HTTP_PORT: "8080"
      HTTP_HOST: "localhost"
      STORE_SSL_DISABLED: "true"
      STORE_ACCESS_KEY: "minio_secret_key"
      STORE_ACCESS_SECRET: "minio_secret_key"
    ports:
      - "8080:8080"
    links:
      - minio
    depends_on:
      - minio
    restart: always
  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_secret_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    ports:
      - published: 9000
        target: 9000
      - published: 9001
        target: 9001
    command: server /data{1...6} --console-address ":9001"
    volumes:
      - data1:/data1
      - data2:/data2
      - data3:/data3
      - data4:/data4
      - data5:/data5
      - data6:/data6
volumes:
  data1:
  data2:
  data3:
  data4:
  data5:
  data6:
